### ISSUE TITLE
Revoir l'Open Graph (OG image) sur X

### ISSUE THREAD

**Issue by Jonathan2051** [etalab/annuaire-entreprises-site#718] opened 2023-10-24 13:49 UTC
- **Problème** : la miniature ne s'affiche pas sur (X / Twitter).

![Image](https://github.com/etalab/annuaire-entreprises-site/assets/73166724/160097f7-5580-492b-998a-d3c95ceac5c5)

**Comment by XavierJp** [comment] 2023-10-25 16:22
Seems like #727 did not fix the issue

**Comment by johangirod** [comment] 2023-10-26 11:15
Yes indeed, but I'm not sure of what we want to achieve here. Should there be a different miniature for every company ? In which case, we'll have to generate png image dynamically. It's not difficult, but it's not a bug fix : the feature never existed before.

**Comment by XavierJp** [comment] 2023-10-26 14:10
Agree with you @johangirod 

For me the only bug fix is on twitter / X where we should at least see the image. 

On creating a custom image for every page it is a different issue / feature request and it is less urgent

**Comment by XavierJp** [comment] 2023-11-09 09:21
According to me we did good enough on this topic and I close this

**Closed by XavierJp** 2023-11-09 09:21 UTC
Labels: bug, SEO
